config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :users
  
  resources :pendings
  
  resources :currentaffairs
  resources :todos do |i|
    resources :tasks
  end


  resources :studies do |i|
    resources :chapters
  end

  root 'home#index'

  get 'createTaskrecord',action: :addTaskrecord,controller: 'taskrecords',as: 'createtaskrecord'

  get ':id',action: :donecurrent,controller: 'currentaffairs',as: 'donecurrentaffairs'

  get 'studies/:study_id/addRevision/:id',action: :addRevision,controller: 'chapters',as: 'addRevision'

  get 'studies/:todo_id/done/:id',action: :addRevision,controller: 'tasks',as: 'done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pending.rb
class Pending < ApplicationRecord
end

app/controllers/pendings_controller.rb
class PendingsController < ApplicationController
  before_action :set_pending, only: [:show, :edit, :update, :destroy]

  # GET /pendings
  # GET /pendings.json
  def index
    @pendings = Pending.all
  end

  # GET /pendings/1
  # GET /pendings/1.json
  def show
  end

  # GET /pendings/new
  def new
    @pending = Pending.new
  end

  # GET /pendings/1/edit
  def edit
  end

  # POST /pendings
  # POST /pendings.json
  def create
    @pending = Pending.new(pending_params)

    respond_to do |format|
      if @pending.save
        format.html { redirect_to @pending, notice: 'Pending was successfully created.' }
        format.json { render :show, status: :created, location: @pending }
      else
        format.html { render :new }
        format.json { render json: @pending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pendings/1
  # PATCH/PUT /pendings/1.json
  def update
    respond_to do |format|
      if @pending.update(pending_params)
        format.html { redirect_to @pending, notice: 'Pending was successfully updated.' }
        format.json { render :show, status: :ok, location: @pending }
      else
        format.html { render :edit }
        format.json { render json: @pending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pendings/1
  # DELETE /pendings/1.json
  def destroy
    @pending.destroy
    respond_to do |format|
      format.html { redirect_to pendings_url, notice: 'Pending was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pending
      @pending = Pending.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pending_params
      params.require(:pending).permit(:name)
    end
end

app/helpers/pendings_helper.rb
module PendingsHelper
end

app/views/pendings/_form.html.haml
= form_for @pending do |f|
  - if @pending.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pending.errors.count, "error")} prohibited this pending from being saved:"
      %ul
        - @pending.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/pendings/edit.html.haml
%h1 Editing pending

= render 'form'

= link_to 'Show', @pending
\|
= link_to 'Back', pendings_path

app/views/pendings/index.html.haml
%h1 Listing pendings

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @pendings.each do |pending|
      %tr
        %td= pending.name
        %td= link_to 'Show', pending
        %td= link_to 'Edit', edit_pending_path(pending)
        %td= link_to 'Destroy', pending, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Pending', new_pending_path

app/views/pendings/new.html.haml
%h1 New pending

= render 'form'

= link_to 'Back', pendings_path

app/views/pendings/show.html.haml
.alert.alert-info= notice if notice= notice

%p
  %b Name:
  = @pending.name

= link_to 'Edit', edit_pending_path(@pending)
\|
= link_to 'Back', pendings_path