config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :users
  
  resources :pendings
  
  resources :currentaffairs
  resources :todos do |i|
    resources :tasks
  end


  resources :studies do |i|
    resources :chapters
  end

  root 'home#index'

  get 'createTaskrecord',action: :addTaskrecord,controller: 'taskrecords',as: 'createtaskrecord'

  get ':id',action: :donecurrent,controller: 'currentaffairs',as: 'donecurrentaffairs'

  get 'studies/:study_id/addRevision/:id',action: :addRevision,controller: 'chapters',as: 'addRevision'

  get 'studies/:todo_id/done/:id',action: :addRevision,controller: 'tasks',as: 'done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
	belongs_to :study
end

app/models/currentaffair.rb
class Currentaffair < ApplicationRecord
end

app/models/pending.rb
class Pending < ApplicationRecord
end

app/models/study.rb
class Study < ApplicationRecord
	has_many :chapters
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo
end

app/models/taskrecord.rb
class Taskrecord < ApplicationRecord

end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :tasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  #
  # GET /tasks.json
  def index
    @tasks = Task.all.order(created_at: 'ASC')
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new

  end

  # GET /tasks/1/edit
  def edit
  end

  def addRevision
    @task=Task.find(params[:id])
    @task.update_attribute(:done,true)
    @book=Study.where(book: @task.name.split(".")[1]).where(subject: @task.name.split(".")[2])
    @chapter=Chapter.where(study_id: @book.ids).where(name: @task.name.split(".").first).first
    x=@chapter.revision+=1
    if @chapter.update_attribute(:revision,x)
      Taskrecord.create(date: Date.today.strftime("%d-%m-%y"))
      redirect_to Todo.find(params[:todo_id]),notice: 'success'
    else
      redirect_to Todo.find(params[:todo_id]),notice: 'Could not add revision'
    end


  end

  # POST /tasks
  # POST /tasks.json
  def create

    @todo=Todo.find(params[:todo_id])
    @task = @todo.tasks.create(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @todo, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @todo=Todo.find(params[:todo_id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to @todo, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all.order(created_at: 'ASC')
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end



  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def taskcounter i
		c=0
		z=0
		Currentaffair.all.each do |ca|
			if ca.todo==i.name && ca.done==true
				c+=1
			end
			if ca.todo==i.name && ca.done!=true
				z+=1
			end
		end

		return [c,z]
	end
end

app/helpers/pendings_helper.rb
module PendingsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/taskrecords_helper.rb
module TaskrecordsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def sub
    return ["History","Geography","Political Science","Economics","Mechanical","Aptitude"]
  end

  def history_select
    arr=[]
    Study.where(subject: 'History').each do |i|
      i.chapters.each do |j|
        str=j.name+'.'+i.book+'.'+'History'
        arr<<str
      end
    end
    return arr
  end

  def geo
    arr=[]
    Study.where(subject: 'Geography').each do |i|
      i.chapters.each do |j|
        str=j.name+'.'+i.book+'.'+'Geography'
        arr<<str
      end
    end
    return arr
  end

  def pol
    arr=[]
    Study.where(subject: 'Political Science').each do |i|
      i.chapters.each do |j|
        str=j.name+'.'+i.book+'.'+'Political Science'
        arr<<str
      end
    end
    return arr
  end

  def mech
    arr=[]
    Study.where(subject: 'Mechanical').each do |i|
      i.chapters.each do |j|
        str=j.name+'.'+i.book+'.'+'Mechanical'
        arr<<str
      end
    end
    return arr
  end


  def eco
    arr=[]
    Study.where(subject: 'Economics').each do |i|
      i.chapters.each do |j|
        str=j.name+'.'+i.book+'.'+'Economics'
        arr<<str
      end
    end
    return arr
  end

  def apti
    arr=[]
    Study.where(subject: 'Aptitude').each do |i|
      i.chapters.each do |j|
        str=j.name+'.'+i.book+'.'+'Aptitude'
        arr<<str
      end
    end
    return arr
  end
end

app/helpers/todos_helper.rb
module TodosHelper

	def taskcounter i
		c=0
		z=0
		Currentaffair.all.each do |ca|
			if ca.todo==i.name && ca.done==true
				c+=1
			end
			if ca.todo==i.name
				z+=1
			end
		end

		a=i.tasks.where(done: true).count+c
		b=i.tasks.count+z

		return (a*100)/b rescue 0
	end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0", :name => "viewport"}/
    %title Mypersonal
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'partials/nav'
    .container
      = yield

app/views/partials/_nav.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to  root_path,class: 'navbar-brand' do
        %span.glyphicon.glyphicon-home
        Home
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to todos_path,class: 'no-style' do
            %span.glyphicon.glyphicon-th-list
            Todo

        %li
          = link_to currentaffairs_path do
            %span.glyphicon.glyphicon-info-sign
            Current Affairs
        %li
          = link_to studies_path do
            %span.glyphicon.glyphicon-book
            Subject
        %li
          = link_to pendings_path do
            %span.glyphicon.glyphicon-tags
            Pending work
        %li
          = link_to new_todo_path do
            %span.glyphicon.glyphicon-plus-sign
            New Todo
        %li
          = link_to new_study_path do
            %span.glyphicon.glyphicon-plus-sign
            New Book
        %li
          = link_to new_currentaffair_path do
            %span.glyphicon.glyphicon-plus-sign
            New Current Affairs


      %form.navbar-form.navbar-left

    / /.navbar-collapse
  / /.container-fluid