config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :users
  
  resources :pendings
  
  resources :currentaffairs
  resources :todos do |i|
    resources :tasks
  end


  resources :studies do |i|
    resources :chapters
  end

  root 'home#index'

  get 'createTaskrecord',action: :addTaskrecord,controller: 'taskrecords',as: 'createtaskrecord'

  get ':id',action: :donecurrent,controller: 'currentaffairs',as: 'donecurrentaffairs'

  get 'studies/:study_id/addRevision/:id',action: :addRevision,controller: 'chapters',as: 'addRevision'

  get 'studies/:todo_id/done/:id',action: :addRevision,controller: 'tasks',as: 'done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/study.rb
class Study < ApplicationRecord
	has_many :chapters
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.all
    @his=Study.where(subject: 'History')
    @geo=Study.where(subject: 'Geography')
    @pol=Study.where(subject: 'Political Science')
    @eco=Study.where(subject: 'Economics')
    @mec=Study.where(subject: 'Mechanical')
    @apti=Study.where(subject: 'Aptitude')
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render :show, status: :created, location: @study }

      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      params.require(:study).permit(:subject, :book)
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.haml
= form_with(model: study) do |form|
  - if study.errors.any?
    #error_explanation
      %h2
        = pluralize(study.errors.count, "error")
        prohibited this study from being saved:
      %ul
        - study.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :subject
    = form.select(:subject,sub,{},{class: 'form-control'})
  .form-group
    = form.label :book
    = form.text_field :book,class: 'form-control'
  .actions
    = form.submit class: 'btn btn-primary'

app/views/studies/edit.html.haml
%h1 Editing Study
= render 'form', study: @study
= link_to 'Show', @study
|
= link_to 'Back', studies_path

app/views/studies/index.html.haml
- if notice
  .alert.alert-info= notice
.row
  .col-md-9
    .row
      .col-md-4
        .panel.panel-primary
          .panel-heading
            %h2 History
          .panel-body
            %button.btn.btn-primary.btn-sm.btn-block{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
              show


      .col-md-4
        .panel.panel-primary
          .panel-heading
            %h2 Geography
          .panel-body
            %button.btn.btn-primary.btn-sm.btn-block{"data-target" => "#myModal2", "data-toggle" => "modal", :type => "button"}
              show
      .col-md-4
        .panel.panel-primary
          .panel-heading
            %h2 Economics
          .panel-body
            %button.btn.btn-primary.btn-sm.btn-block{"data-target" => "#myModal3", "data-toggle" => "modal", :type => "button"}
              show
    .row
      .col-md-4
        .panel.panel-primary
          .panel-heading
            %h2 Political science
          .panel-body
            %button.btn.btn-primary.btn-sm.btn-block{"data-target" => "#myModal4", "data-toggle" => "modal", :type => "button"}
              show
      .col-md-4
        .panel.panel-primary
          .panel-heading
            %h2 Mechanical
          .panel-body
            %button.btn.btn-primary.btn-sm.btn-block{"data-target" => "#myModal5", "data-toggle" => "modal", :type => "button"}
              show
      .col-md-4
        .panel.panel-primary
          .panel-heading
            %h2 Aptitude
          .panel-body
            %button.btn.btn-primary.btn-sm.btn-block{"data-target" => "#myModal6", "data-toggle" => "modal", :type => "button"}
              show
  .col-md-3
    = link_to new_study_path,class: 'btn btn-primary' do
      %span.glyphicon.glyphicon-plus-sign
      Edit

    .row


#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title History
      .modal-body
        %table.table
          %tr
            %th Book
            %th Edit
            %th Delete

          - @his.each do |i|
            %tr
              %td
                = link_to i ,class: 'no-style' do
                  %span.glyphicon.glyphicon-book
                  = i.book
              %td
                = link_to edit_study_path(i) ,class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-wrench
                  Edit
              %td
                = link_to i,method: :delete ,class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove
                  Delete
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
#myModal2.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel2.modal-title Geography
      .modal-body
        %table.table
          %tr
            %th Book
            %th Edit
            %th Delete

          - @geo.each do |i|
            %tr
              %td
                = link_to i ,class: 'no-style' do
                  %span.glyphicon.glyphicon-book
                  = i.book
              %td
                = link_to edit_study_path(i) ,class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-wrench
                  Edit
              %td
                = link_to i,method: :delete ,class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove
                  Delete
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
#myModal3.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel3.modal-title Economics
      .modal-body
        %table.table
          %tr
            %th Book
            %th Edit
            %th Delete

          - @eco.each do |i|
            %tr
              %td
                = link_to i ,class: 'no-style' do
                  %span.glyphicon.glyphicon-book
                  = i.book
              %td
                = link_to edit_study_path(i) ,class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-wrench
                  Edit
              %td
                = link_to i,method: :delete ,class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove
                  Delete
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
#myModal4.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel4.modal-title Political science
      .modal-body
        %table.table
          %tr
            %th Book
            %th Edit
            %th Delete

          - @pol.each do |i|
            %tr
              %td
                = link_to i ,class: 'no-style' do
                  %span.glyphicon.glyphicon-book
                  = i.book
              %td
                = link_to edit_study_path(i) ,class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-wrench
                  Edit
              %td
                = link_to i,method: :delete ,class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove
                  Delete
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
#myModal5.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel5.modal-title Mechanical
      .modal-body
        %table.table
          %tr
            %th Book
            %th Edit
            %th Delete

          - @mec.each do |i|
            %tr
              %td
                = link_to i ,class: 'no-style' do
                  %span.glyphicon.glyphicon-book
                  = i.book
              %td
                = link_to edit_study_path(i) ,class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-wrench
                  Edit
              %td
                = link_to i,method: :delete ,class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove
                  Delete
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
#myModal6.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel6.modal-title Aptitude
      .modal-body
        %table.table
          %tr
            %th Book
            %th Edit
            %th Delete

          - @apti.each do |i|
            %tr
              %td
                = link_to i ,class: 'no-style' do
                  %span.glyphicon.glyphicon-book
                  = i.book
              %td
                = link_to edit_study_path(i) ,class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-wrench
                  Edit
              %td
                = link_to i,method: :delete ,class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove
                  Delete
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/studies/new.html.haml
.row
  .col-md-9
    .panel.panel-default
      .panel-heading
        %h4 New Study
      .panel-body
        = render 'form', study: @study
      .panel-footer
        = link_to 'Back', studies_path,class: 'btn btn-info'
  .col-md-3

app/views/studies/show.html.haml
.row
  .col-md-9
    .panel.panel-primary
      .panel-heading
        %h2
          %span.glyphicon.glyphicon-book
          = @study.subject
          = @study.book
          = link_to 'Edit', edit_study_path(@study),class: 'btn btn-primary'
      .panel-body
        %table.table
          %tr
            %th
              Chapter
            %th
              No of revision
            %th
              Action
          - @study.chapters.each do |i|
            %tr
              %td= i.name
              %td= i.revision
              %td
                = link_to addRevision_path(@study,i),data: {confirm: 'add revision'} ,class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-plus
                  Add revision



  .col-md-3
    = render 'chapters/form'