config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :users
  
  resources :pendings
  
  resources :currentaffairs
  resources :todos do |i|
    resources :tasks
  end


  resources :studies do |i|
    resources :chapters
  end

  root 'home#index'

  get 'createTaskrecord',action: :addTaskrecord,controller: 'taskrecords',as: 'createtaskrecord'

  get ':id',action: :donecurrent,controller: 'currentaffairs',as: 'donecurrentaffairs'

  get 'studies/:study_id/addRevision/:id',action: :addRevision,controller: 'chapters',as: 'addRevision'

  get 'studies/:todo_id/done/:id',action: :addRevision,controller: 'tasks',as: 'done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :tasks
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all.order(created_at: 'ASC')
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end



  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name)
    end
end

app/helpers/todos_helper.rb
module TodosHelper

	def taskcounter i
		c=0
		z=0
		Currentaffair.all.each do |ca|
			if ca.todo==i.name && ca.done==true
				c+=1
			end
			if ca.todo==i.name
				z+=1
			end
		end

		a=i.tasks.where(done: true).count+c
		b=i.tasks.count+z

		return (a*100)/b rescue 0
	end
end

app/views/todos/_form.html.haml
= form_for @todo do |f|
  - if @todo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@todo.errors.count, "error")} prohibited this todo from being saved:"
      %ul
        - @todo.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name,class: 'form-control'
  .actions
    = f.submit 'Save',class: 'btn btn-primary'

app/views/todos/edit.html.haml
%h1 Editing todo

= render 'form'

= link_to 'Show', @todo
\|
= link_to 'Back', todos_path

app/views/todos/index.html.haml
- if notice
  .alert.alert-info= notice
.row
  .col-md-9
    - @todos.each_slice(3) do |i|
      .row
        .col-md-4
          - if i[0]!=nil && i[0].tasks!=nil
            .panel.panel-primary
              .panel-heading
                %h3

                  = i[0].name
                  %span.glyphicon.glyphicon-pushpin
              .panel-body
                .progress
                  .progress-bar.progress-bar-striped.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{taskcounter(i[0])}", :role => "progressbar", :style => "width: #{taskcounter(i[0])}%"}
                    = taskcounter(i[0])
                    \%


              .panel-footer
                = link_to i[0],class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-info-sign
                  Show
                = link_to edit_todo_path(i[0]),class: 'btn btn-primary' do
                  %span.glyphicon.glyphicon-wrench
                  edit
                = link_to i[0],method: :delete,data: {confirm: 'are you sure'},class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove-circle
                  Delete

        .col-md-4
          - if i[1]!=nil
            .panel.panel-primary
              .panel-heading
                %h3
                  = i[1].name
                  %span.glyphicon.glyphicon-pushpin

              .panel-body


                .progress
                  .progress-bar.progress-bar-striped.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{taskcounter(i[1])}", :role => "progressbar", :style => "width: #{taskcounter(i[1])}%;"}
                    = taskcounter(i[1])
                    \%
              .panel-footer
                = link_to i[1],class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-info-sign
                  Show
                = link_to edit_todo_path(i[1]),class: 'btn btn-primary' do
                  %span.glyphicon.glyphicon-wrench
                  edit
                = link_to i[1],method: :delete,data: {confirm: 'are you sure'},class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove-circle
                  Delete
        .col-md-4
          - if i[2]!=nil
            .panel.panel-primary
              .panel-heading
                %h3
                  = i[2].name
                  %span.glyphicon.glyphicon-pushpin
              .panel-body


                .progress
                  .progress-bar.progress-bar-striped.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{taskcounter(i[2])}", :role => "progressbar", :style => "width: #{taskcounter(i[2])}%;"}
                    = taskcounter(i[2])
                    \%
              .panel-footer
                = link_to i[2],class: 'btn btn-info' do
                  %span.glyphicon.glyphicon-info-sign
                  Show
                = link_to edit_todo_path(i[2]),class: 'btn btn-primary' do
                  %span.glyphicon.glyphicon-wrench
                  edit
                = link_to i[2],method: :delete,data: {confirm: 'are you sure'},class: 'btn btn-danger' do
                  %span.glyphicon.glyphicon-remove-circle
                  Delete




  .col-md-3

app/views/todos/new.html.haml
.row
  .col-md-9
    .panel.panel-primary
      .panel-heading
        %h1 New todo
      .panel-body
        = render 'form'
      .panel-footer
        = link_to todos_path,class: 'btn btn-primary' do
          %span.glyphicon.glyphicon-arrow-left
          back

app/views/todos/show.html.haml
- if notice
  .alert.alert-info= notice

.row
  .col-md-9
    .panel.panel-primary
      .panel-heading
        %h3
          %span.glyphicon.glyphicon-paperclip

          = @todo.name
      .panel-body
        %table.table
          %tr
            %th Name
            %th action
            %th action
          - @todo.tasks.each do |i|
            %tr
              %td

                - if i.done==true
                  .span.glyphicon.glyphicon-ok
                  %del= i.name
                - else
                  %span.glyphicon.glyphicon-minus
                  = i.name
              - if i.done!=true
                %td
                  = link_to done_path(@todo,i),class: 'btn btn-info' do
                    %span.glyphicon.glyphicon-thumbs-up
                    Done
                %td= link_to 'delete',[@todo,i],method: :delete,data: {confirm: 'sure'},class: 'btn btn-danger'
              - else
                %td
                %td= link_to 'delete',[@todo,i],method: :delete,data: {confirm: 'sure'},class: 'btn btn-danger'
          - Currentaffair.all.each do |i|
            %tr
              - if i.todo==@todo.name
                - if i.done==true
                  %td
                    %span.glyphicon.glyphicon-ok
                    %del= i.name.strftime("%d-%m-%y")
                  %td
                  %td= link_to "delete",i,method: :delete,class: 'btn btn-danger'
                - else
                  %td
                    %span.glyphicon.glyphicon-minus
                    = i.name.strftime("%d-%m-%y")
                  %td
                    = link_to donecurrentaffairs_path(i) ,class: 'btn btn-info' do
                      %span.glyphicon.glyphicon-thumbs-up
                      Done
                  %td= link_to "delete",i,method: :delete,class: 'btn btn-danger'




  .col-md-3

    .row
      %button.btn.btn-primary.btn-md.btn-block{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
        History
    .row
      %button.btn.btn-primary.btn-md.btn-block{"data-target" => "#myModal2", "data-toggle" => "modal", :type => "button"}
        Geography
    .row
      %button.btn.btn-primary.btn-md.btn-block{"data-target" => "#myModal3", "data-toggle" => "modal", :type => "button"}
        Political science
    .row
      %button.btn.btn-primary.btn-md.btn-block{"data-target" => "#myModal4", "data-toggle" => "modal", :type => "button"}
        Economics
    .row
      %button.btn.btn-primary.btn-md.btn-block{"data-target" => "#myModal5", "data-toggle" => "modal", :type => "button"}
        Mechanical
    .row
      %button.btn.btn-primary.btn-md.btn-block{"data-target" => "#myModal6", "data-toggle" => "modal", :type => "button"}
        Aptitude

/ Modal
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title History
      .modal-body
        = render 'tasks/form'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close


#myModal2.modal.fade{"aria-labelledby" => "myModalLabel2", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel2.modal-title Geography
      .modal-body
        = render 'tasks/form_geo'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close



#myModal3.modal.fade{"aria-labelledby" => "myModalLabel2", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel3.modal-title Political science
      .modal-body
        = render 'tasks/form_poi'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

#myModal4.modal.fade{"aria-labelledby" => "myModalLabel2", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel4.modal-title Eco
      .modal-body
        = render 'tasks/form_eco'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

#myModal5.modal.fade{"aria-labelledby" => "myModalLabel2", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel5.modal-title Mechanical
      .modal-body
        = render 'tasks/form_mech'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

#myModal6.modal.fade{"aria-labelledby" => "myModalLabel2", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel6.modal-title Aptitude
      .modal-body
        = render 'tasks/form_apti'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close